#!/bin/bash
# Exit immediately if a command fails
set -e

echo "Running Ruff format..."
pixi run ruff format

echo "Running Ruff check..."
pixi run ruff check

echo "Running Mypy..."
pixi run mypy .

echo "All checks passed!"
